name: fluttask
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 3.12.1
  sqflite: 1.3.1+1
  path: 1.7.0
  mask_text_input_formatter: 1.1.0
  dio: 3.0.10

flutter:
  uses-material-design: true